/**
 * OpenRefs D1 schema (Drizzle / SQLite).
 *
 * Two invariants hold across this file and MUST hold for anything added later:
 *
 * 1. Deletion is a feature. Every table holding workspace data is reachable
 *    from `workspaces` by a chain of `onDelete: "cascade"` foreign keys, so
 *    deleting a workspace row empties D1 of that tenant. KV and R2 are purged
 *    separately by prefix (`ws:<workspaceId>:` / `ws:<workspaceId>/`).
 * 2. Column names are written out explicitly in snake_case rather than relying
 *    on a `casing` setting, so drizzle-kit and the runtime client can never
 *    disagree about what a column is called.
 *
 * SQLite enforces foreign keys only when `PRAGMA foreign_keys = ON`. D1 sets
 * this for you; `wrangler d1 execute` sessions do not always.
 */
import { relations, sql } from "drizzle-orm";
import {
  index,
  integer,
  primaryKey,
  real,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

/** Text primary key, defaulted to a UUID v4 generated by WebCrypto. */
const id = () =>
  text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID());

/** Epoch milliseconds, defaulted to insert time. */
const createdAt = () =>
  integer("created_at", { mode: "timestamp_ms" })
    .notNull()
    .$defaultFn(() => new Date());

export const WORKSPACE_ROLES = ["owner", "admin", "member"] as const;
export type WorkspaceRole = (typeof WORKSPACE_ROLES)[number];

export const JOB_STATUSES = ["pending", "running", "done", "failed"] as const;
export type JobStatus = (typeof JOB_STATUSES)[number];

export const AUDIT_STATUSES = [
  "pending",
  "running",
  "done",
  "failed",
] as const;
export type AuditStatus = (typeof AUDIT_STATUSES)[number];

export const DEVICES = ["desktop", "mobile"] as const;
export type Device = (typeof DEVICES)[number];

/* -------------------------------------------------------------------------- */
/* Identity                                                                    */
/* -------------------------------------------------------------------------- */

export const users = sqliteTable("users", {
  id: id(),
  email: text("email").notNull().unique(),
  /** PBKDF2-SHA256, 600k iterations. Format owned by the auth module. */
  passwordHash: text("password_hash").notNull(),
  createdAt: createdAt(),
});

export const sessions = sqliteTable(
  "sessions",
  {
    /** Opaque session id; the cookie carries this value. */
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    // Hot path: "log this user out everywhere" and session cleanup.
    index("sessions_user_id_idx").on(t.userId),
    index("sessions_expires_at_idx").on(t.expiresAt),
  ],
);

/* -------------------------------------------------------------------------- */
/* Workspaces                                                                  */
/* -------------------------------------------------------------------------- */

export const workspaces = sqliteTable("workspaces", {
  id: id(),
  name: text("name").notNull(),
  /**
   * DataForSEO credentials, AES-256-GCM encrypted with APP_MASTER_KEY in the
   * `v1$iv$ciphertext` format from src/worker/lib/crypto.ts. Never selected
   * into an API response.
   */
  dfsLoginEnc: text("dfs_login_enc"),
  dfsPasswordEnc: text("dfs_password_enc"),
  /**
   * Monthly ceiling in USD enforced by the DataForSEO client before it spends.
   * 0 blocks every paid call; cached reads are always allowed.
   */
  spendCapUsd: real("spend_cap_usd").notNull().default(25),
  settingsJson: text("settings_json", { mode: "json" })
    .$type<Record<string, unknown>>()
    .notNull()
    .default(sql`'{}'`),
  createdAt: createdAt(),
});

export const workspaceMembers = sqliteTable(
  "workspace_members",
  {
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    role: text("role", { enum: WORKSPACE_ROLES }).notNull().default("member"),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.workspaceId, t.userId] }),
    // Both directions are hot: "who is in this workspace" and the
    // workspace-switcher's "what can this user see".
    index("workspace_members_workspace_id_idx").on(t.workspaceId),
    index("workspace_members_user_id_idx").on(t.userId),
  ],
);

export const invites = sqliteTable(
  "invites",
  {
    id: id(),
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    email: text("email").notNull(),
    /** SHA-256 of the invite token. The raw token only ever exists in the link. */
    tokenHash: text("token_hash").notNull().unique(),
    role: text("role", { enum: WORKSPACE_ROLES }).notNull().default("member"),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
    createdAt: createdAt(),
  },
  (t) => [index("invites_workspace_id_idx").on(t.workspaceId)],
);

export const apiKeys = sqliteTable(
  "api_keys",
  {
    id: id(),
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    /** SHA-256 of the key. The plaintext is shown once, at creation. */
    keyHash: text("key_hash").notNull().unique(),
    createdAt: createdAt(),
    lastUsedAt: integer("last_used_at", { mode: "timestamp_ms" }),
  },
  (t) => [index("api_keys_workspace_id_idx").on(t.workspaceId)],
);

/* -------------------------------------------------------------------------- */
/* Projects (a site you own)                                                   */
/* -------------------------------------------------------------------------- */

export const projects = sqliteTable(
  "projects",
  {
    id: id(),
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    /** Bare hostname, no scheme, e.g. "example.com". */
    domain: text("domain").notNull(),
    name: text("name").notNull(),
    /** DataForSEO location/language codes. Defaults are UK / English. */
    locationCode: integer("location_code").notNull().default(2826),
    languageCode: text("language_code").notNull().default("en"),
    settingsJson: text("settings_json", { mode: "json" })
      .$type<Record<string, unknown>>()
      .notNull()
      .default(sql`'{}'`),
    createdAt: createdAt(),
  },
  (t) => [index("projects_workspace_id_idx").on(t.workspaceId)],
);

/* -------------------------------------------------------------------------- */
/* Keyword collections (ad-hoc research)                                       */
/* -------------------------------------------------------------------------- */

export const collections = sqliteTable(
  "collections",
  {
    id: id(),
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    createdAt: createdAt(),
  },
  (t) => [index("collections_workspace_id_idx").on(t.workspaceId)],
);

export const collectionKeywords = sqliteTable(
  "collection_keywords",
  {
    collectionId: text("collection_id")
      .notNull()
      .references(() => collections.id, { onDelete: "cascade" }),
    keyword: text("keyword").notNull(),
    /** Search volume at the moment it was saved, so lists stay comparable. */
    volumeSnapshot: integer("volume_snapshot"),
    addedAt: integer("added_at", { mode: "timestamp_ms" })
      .notNull()
      .$defaultFn(() => new Date()),
  },
  (t) => [
    primaryKey({ columns: [t.collectionId, t.keyword] }),
    index("collection_keywords_collection_id_idx").on(t.collectionId),
  ],
);

/* -------------------------------------------------------------------------- */
/* Rank tracking                                                               */
/* -------------------------------------------------------------------------- */

export const trackedKeywords = sqliteTable(
  "tracked_keywords",
  {
    id: id(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    keyword: text("keyword").notNull(),
    locationCode: integer("location_code").notNull(),
    languageCode: text("language_code").notNull(),
    device: text("device", { enum: DEVICES }).notNull().default("desktop"),
    createdAt: createdAt(),
  },
  (t) => [
    index("tracked_keywords_project_id_idx").on(t.projectId),
    uniqueIndex("tracked_keywords_unique_idx").on(
      t.projectId,
      t.keyword,
      t.locationCode,
      t.languageCode,
      t.device,
    ),
  ],
);

export const rankSnapshots = sqliteTable(
  "rank_snapshots",
  {
    id: id(),
    trackedKeywordId: text("tracked_keyword_id")
      .notNull()
      .references(() => trackedKeywords.id, { onDelete: "cascade" }),
    /** ISO date, `YYYY-MM-DD`, so daily series group without timezone maths. */
    date: text("date").notNull(),
    /** Null means "not in the fetched results" — distinct from position 100. */
    position: integer("position"),
    url: text("url"),
    serpFeaturesJson: text("serp_features_json", { mode: "json" })
      .$type<string[]>()
      .notNull()
      .default(sql`'[]'`),
    createdAt: createdAt(),
  },
  (t) => [
    // The history chart's only query shape: one keyword, ordered by date.
    index("rank_snapshots_keyword_date_idx").on(t.trackedKeywordId, t.date),
  ],
);

/* -------------------------------------------------------------------------- */
/* Site audit                                                                  */
/* -------------------------------------------------------------------------- */

export const audits = sqliteTable(
  "audits",
  {
    id: id(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    /** DataForSEO OnPage task id, polled by the jobs sweeper. */
    dfsTaskId: text("dfs_task_id"),
    status: text("status", { enum: AUDIT_STATUSES }).notNull().default("pending"),
    /** Rollup only. Raw crawled pages live in R2 under ws:<workspaceId>/. */
    summaryJson: text("summary_json", { mode: "json" })
      .$type<Record<string, unknown>>()
      .notNull()
      .default(sql`'{}'`),
    createdAt: createdAt(),
  },
  (t) => [
    index("audits_project_id_idx").on(t.projectId),
    index("audits_dfs_task_id_idx").on(t.dfsTaskId),
  ],
);

/* -------------------------------------------------------------------------- */
/* Metering                                                                    */
/* -------------------------------------------------------------------------- */

export const apiUsage = sqliteTable(
  "api_usage",
  {
    id: id(),
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    /** DataForSEO path, e.g. "keywords_data/google_ads/search_volume/live". */
    endpoint: text("endpoint").notNull(),
    /** Cost reported by DataForSEO. Cache hits are recorded at 0. */
    costUsd: real("cost_usd").notNull().default(0),
    cached: integer("cached", { mode: "boolean" }).notNull().default(false),
    createdAt: createdAt(),
  },
  (t) => [
    // Spend-cap check and the usage report both scan one workspace by time.
    index("api_usage_workspace_created_idx").on(t.workspaceId, t.createdAt),
  ],
);

/* -------------------------------------------------------------------------- */
/* Background work (cron + this table; no Queues, no Durable Objects)          */
/* -------------------------------------------------------------------------- */

export const jobs = sqliteTable(
  "jobs",
  {
    id: id(),
    /** Discriminator owned by the job handlers, e.g. "rank_check". */
    type: text("type").notNull(),
    /**
     * Nullable so housekeeping jobs can exist without a tenant. When set, the
     * cascade guarantees a deleted workspace leaves no queued work behind —
     * this column exists for that reason and must be populated by any job
     * that touches workspace data.
     */
    workspaceId: text("workspace_id").references(() => workspaces.id, {
      onDelete: "cascade",
    }),
    payloadJson: text("payload_json", { mode: "json" })
      .$type<Record<string, unknown>>()
      .notNull()
      .default(sql`'{}'`),
    /** Earliest time the sweeper may pick this up. Doubles as the retry backoff. */
    runAt: integer("run_at", { mode: "timestamp_ms" })
      .notNull()
      .$defaultFn(() => new Date()),
    status: text("status", { enum: JOB_STATUSES }).notNull().default("pending"),
    attempts: integer("attempts").notNull().default(0),
    lastError: text("last_error"),
    createdAt: createdAt(),
  },
  (t) => [
    // The sweeper's only query: pending jobs whose run_at has passed.
    index("jobs_status_run_at_idx").on(t.status, t.runAt),
    index("jobs_workspace_id_idx").on(t.workspaceId),
  ],
);

/* -------------------------------------------------------------------------- */
/* Search Console                                                              */
/* -------------------------------------------------------------------------- */

export const gscConnections = sqliteTable("gsc_connections", {
  /** One connection per project, so the project id is the key. */
  projectId: text("project_id")
    .primaryKey()
    .references(() => projects.id, { onDelete: "cascade" }),
  /** Google refresh token, AES-256-GCM encrypted with APP_MASTER_KEY. */
  refreshTokenEnc: text("refresh_token_enc").notNull(),
  /** GSC property URL, e.g. "sc-domain:example.com". */
  property: text("property").notNull(),
  /** Kept if the connecting user is later deleted — the project keeps its data. */
  connectedBy: text("connected_by").references(() => users.id, {
    onDelete: "set null",
  }),
  createdAt: createdAt(),
});

/* -------------------------------------------------------------------------- */
/* AI visibility                                                               */
/* -------------------------------------------------------------------------- */

export const aiPrompts = sqliteTable(
  "ai_prompts",
  {
    id: id(),
    projectId: text("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    prompt: text("prompt").notNull(),
    /** Engine ids to run this prompt against. */
    enginesJson: text("engines_json", { mode: "json" })
      .$type<string[]>()
      .notNull()
      .default(sql`'[]'`),
    createdAt: createdAt(),
  },
  (t) => [index("ai_prompts_project_id_idx").on(t.projectId)],
);

export const aiSnapshots = sqliteTable(
  "ai_snapshots",
  {
    id: id(),
    promptId: text("prompt_id")
      .notNull()
      .references(() => aiPrompts.id, { onDelete: "cascade" }),
    /** ISO date, `YYYY-MM-DD`. */
    date: text("date").notNull(),
    engine: text("engine").notNull(),
    mentioned: integer("mentioned", { mode: "boolean" }).notNull().default(false),
    citationsJson: text("citations_json", { mode: "json" })
      .$type<unknown[]>()
      .notNull()
      .default(sql`'[]'`),
    createdAt: createdAt(),
  },
  (t) => [index("ai_snapshots_prompt_date_idx").on(t.promptId, t.date)],
);

/* -------------------------------------------------------------------------- */
/* Relations                                                                   */
/* -------------------------------------------------------------------------- */

export const usersRelations = relations(users, ({ many }) => ({
  sessions: many(sessions),
  memberships: many(workspaceMembers),
}));

export const sessionsRelations = relations(sessions, ({ one }) => ({
  user: one(users, { fields: [sessions.userId], references: [users.id] }),
}));

export const workspacesRelations = relations(workspaces, ({ many }) => ({
  members: many(workspaceMembers),
  invites: many(invites),
  apiKeys: many(apiKeys),
  projects: many(projects),
  collections: many(collections),
  apiUsage: many(apiUsage),
  jobs: many(jobs),
}));

export const workspaceMembersRelations = relations(
  workspaceMembers,
  ({ one }) => ({
    workspace: one(workspaces, {
      fields: [workspaceMembers.workspaceId],
      references: [workspaces.id],
    }),
    user: one(users, {
      fields: [workspaceMembers.userId],
      references: [users.id],
    }),
  }),
);

export const projectsRelations = relations(projects, ({ one, many }) => ({
  workspace: one(workspaces, {
    fields: [projects.workspaceId],
    references: [workspaces.id],
  }),
  trackedKeywords: many(trackedKeywords),
  audits: many(audits),
  aiPrompts: many(aiPrompts),
}));

export const collectionsRelations = relations(collections, ({ one, many }) => ({
  workspace: one(workspaces, {
    fields: [collections.workspaceId],
    references: [workspaces.id],
  }),
  keywords: many(collectionKeywords),
}));

export const collectionKeywordsRelations = relations(
  collectionKeywords,
  ({ one }) => ({
    collection: one(collections, {
      fields: [collectionKeywords.collectionId],
      references: [collections.id],
    }),
  }),
);

export const trackedKeywordsRelations = relations(
  trackedKeywords,
  ({ one, many }) => ({
    project: one(projects, {
      fields: [trackedKeywords.projectId],
      references: [projects.id],
    }),
    snapshots: many(rankSnapshots),
  }),
);

export const rankSnapshotsRelations = relations(rankSnapshots, ({ one }) => ({
  trackedKeyword: one(trackedKeywords, {
    fields: [rankSnapshots.trackedKeywordId],
    references: [trackedKeywords.id],
  }),
}));

export const aiPromptsRelations = relations(aiPrompts, ({ one, many }) => ({
  project: one(projects, {
    fields: [aiPrompts.projectId],
    references: [projects.id],
  }),
  snapshots: many(aiSnapshots),
}));

export const aiSnapshotsRelations = relations(aiSnapshots, ({ one }) => ({
  prompt: one(aiPrompts, {
    fields: [aiSnapshots.promptId],
    references: [aiPrompts.id],
  }),
}));
